services:
  # IP Service (Backend)
  - type: web
    name: server
    env: node
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGO_URI
        sync: false # User must provide this in dashboard
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: server
          property: url

